# Generated by Django 4.1.3 on 2022-12-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('time_interval', models.CharField(blank=True, max_length=20, null=True)),
                ('time_period', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
