# Generated by Django 4.1.3 on 2022-12-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('postalCode', models.CharField(max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('addAmenity', models.CharField(blank=True, max_length=100, null=True)),
                ('addQuantity', models.CharField(blank=True, max_length=100, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='studio_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='studio_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='studio_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='studio_images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='studio_images/')),
                ('distance', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
